#%RAML 1.0
title: shoppies-api
version: 1.0.0
baseUri: http://localhost:8008/api
mediaType: application/json
types:
    Nomination:
        description: A movie nomination
        type: object
        properties:
            _id:
                description: Generated nominationID
                type: string
                example: tt2872732tt2872732tt2872732
            imdbID:
                description: Movie ID from imdb
                type: string
                example: tt2872732
            userID:
                description: A user's ID
                type: string
                example: tt2872732tt2
                maxLength: 12
                minLength: 12
/nominations:
    description: Nomination endpoint
    delete:
        description: Delete a nomination
        responses:
            200:
                description: |
                    Nomination deleted successfully
                body:
                    application/json:
                      description: Success request response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: Nomination[]
                        error:
                            description: Response error
                            type: boolean
                            example: false
                        message:
                            description: Response message
                            type: string
                            example: Nomination deleted successfully
            400:
                description: |
                    Missen field
                body:
                    application/json:
                      description: Field error response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: nil
                        error:
                            description: Response error
                            type: boolean
                            example: true
                        message:
                            description: Response message
                            type: string
                            example: All fields are required
            404:
                description: |
                    Nomination not found
                body:
                    application/json:
                      description: Not found error response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: nil
                        error:
                            description: Response error
                            type: boolean
                            example: true
                        message:
                            description: Response message
                            type: string
                            example: Nomination not found
            500:
                description: |
                  Internal Server Error
                body:
                  application/json:
                      description: Error response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: nil
                        error:
                            description: Response error
                            type: boolean
                            example: true
                        message:
                            description: Response message
                            type: string
                            example: Internal server error
    get:
        description: Get all nominations
        responses:
            200:
                description: |
                    Nominations fetched successfully
                body:
                    application/json:
                      description: Success request response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: Nomination[]
                        error:
                            description: Response error
                            type: boolean
                            example: false
                        message:
                            description: Response message
                            type: string
                            example: Nominations fetched successfully
            404:
                description: |
                    No nominations found
                body:
                    application/json:
                      description: Not found error response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: nil
                        error:
                            description: Response error
                            type: boolean
                            example: true
                        message:
                            description: Response message
                            type: string
                            example: No nominations found
            500:
                description: |
                  Internal Server Error
                body:
                  application/json:
                      description: Error response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: nil
                        error:
                            description: Response error
                            type: boolean
                            example: true
                        message:
                            description: Response message
                            type: string
                            example: Internal server error
    post:
      description: Save a nomination
      body:
        application/json: Nomination
      responses:
        201:
          description: |
              Successful nomination
          body:
              application/json:
                  description: Success request response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: Nomination[]
                    error:
                        description: Response error
                        type: boolean
                        example: false
                    message:
                        description: Response message
                        type: string
                        example: Movie nominated successfully
        400:
            description: |
                Missen field
            body:
                application/json:
                  description: Field error response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: All fields are required
        409:
            description: |
                Nomination already exists
            body:
                application/json:
                  description: Duplicate request response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: You have already nominated this movie
        410:
            description: |
                Limit reached
            body:
                application/json:
                  description: Limit request response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: You have made the maximum number of nominations
        500:
            description: |
              Internal Server Error
            body:
              application/json:
                  description: Error response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: Internal server error
