#%RAML 1.0
title: shoppies-api
version: 1.0.0
baseUri: http://localhost:8008/api
mediaType: application/json
types:
    MovieID:
        description: Movie ID from imdb
        type: string
        example: tt2872732
    # Movie:
    #     description: A movie
    #     type: object
    #     properties:
    #       actors:
    #         description: Movie actors
    #         type: array
    #         example: [Scarlett Johansson, Morgan Freeman, Choi Min-sik, Amr Waked]
    #       genre:
    #         description: Movie genre
    #         type: array
    #         example: [Action, Thriller, Sci-Fi]
    #       imdbID: MovieID
    #       imdbRating:
    #         description: Movie rating from IMDB rating
    #         type: string
    #         pattern: ^(([1-9][0-9]*)|[0])[.]([0-9]{1})$
    #         example: "6.4"
    #       plot:
    #         description: Movie plot
    #         type: string
    #         example: |
    #           A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.
    #       released:
    #           description: Movie release year
    #           type: string
    #           pattern: ^\d{4}$
    #           example: "2014"
    #       title:
    #         description: Movie title
    #         type: string
    #         example: Lucy
    Nomination:
        description: Movie nominations
        type: object
        properties:
            category:
                description: Nomination category
                type: string
                enum:
                  [Best Actor/Best Actress,
                  Best Adapted Screenplay,
                  Best Original Screenplay,
                  Best Animated Feature Film,
                  Best Cinematography,
                  Best Costume Design,
                  Best Director,
                  Best Film Editing,
                  Best Foreign Language Film,
                  Best Makeup]
                example: Best Makeup
            email:
                description: A user's email address
                type: string
                pattern: ^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$
                example: "john.doe@example.com"
            id:
                description: Concatenation of imdbIDs
                type: string
                example: tt2872732tt2872732tt2872732
            movieID: MovieID
/nominations:
    description: Nomination endpoint
    get:
        description: Get all nominations
        responses:
            200:
                description: |
                    Nominations fetched successfully
                body:
                    application/json:
                      description: Success request response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: Nomination[]
                        error:
                            description: Response error
                            type: boolean
                            example: false
                        message:
                            description: Response message
                            type: string
                            example: Nominations fetched successfully
            404:
                description: |
                    No application found
                body:
                    application/json:
                      description: Not found error response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: nil
                        error:
                            description: Response error
                            type: boolean
                            example: true
                        message:
                            description: Response message
                            type: string
                            example: No nominations found
            500:
                description: |
                  Internal Server Error
                body:
                  application/json:
                      description: Error response
                      type: object
                      properties:
                        data:
                            description: Response data
                            type: nil
                        error:
                            description: Response error
                            type: boolean
                            example: true
                        message:
                            description: Response message
                            type: string
                            example: Internal server error
    post:
      description: Save a nomination
      body:
        application/json: Nomination
      responses:
        201:
          description: |
              Successful nomination
          body:
              application/json:
                  description: Success request response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: Nomination
                    error:
                        description: Response error
                        type: boolean
                        example: false
                    message:
                        description: Response message
                        type: string
                        example: Movie nominated successfully
        400:
            description: |
                Missen field
            body:
                application/json:
                  description: Field error response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: All fields are required
        401:
            description: |
                Invalid email
            body:
                application/json:
                  description: Field error response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: Email is invalid
        402:
            description: |
                Invalid category
            body:
                application/json:
                  description: Field error response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: Invalid category
        409:
            description: |
                Nomination already exists
            body:
                application/json:
                  description: Duplicate request response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: You have already nominated this movie for this category
        500:
            description: |
              Internal Server Error
            body:
              application/json:
                  description: Error response
                  type: object
                  properties:
                    data:
                        description: Response data
                        type: nil
                    error:
                        description: Response error
                        type: boolean
                        example: true
                    message:
                        description: Response message
                        type: string
                        example: Internal server error
